baseURL = "eastuttgart.org/"
theme = "local-ea-template"

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be th english site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "EA Stuttgart"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Stuttgart"
  strapline = "Doing good better."

  ## -- EA GROUP INFO -- ##
  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism Stuttgart"
  orgLocations = "Stuttgart"
  contactEmail = "stuttgartea@gmail.com"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effective Altruism"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- Page Headers -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  #leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  #firstSectionHeader = "Doing good better"
  #secondSectionHeader = "Building a community"
  #thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  leadText = "Thank you for your interest in effective altruism. Please contact us via following form."
  senderName = "Your name (required):"
  senderEmail = "Your email (required):"
  emailSubject = "Subject of your Message:"
  emailMessage = "Your Message:"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonText = "Find us on Facebook"
  firstButtonLink = "https://www.facebook.com/groups/eastuttgart/"
  secondButtonText = "E-Mail Newsletter"
  secondButtonLink = "https://groups.google.com/d/forum/eastuttgart"
  # Remove the # before the text to add the optional Meetup button
  meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/groups/eastuttgart/"
  #twitterUrl = ""
  meetupUrl = "https://www.meetup.com/Stuttgart-Effective-Altruism-Meetup"


  [Languages.de]
  languageCode = "de"
  title = "Die beste EA Webseite"
  weight = 2


  [Languages.de.general]
  fullTitle = "EA Stuttgart"
  strapline = "Gutes besser tun."

  [Languages.de.groupinfo]
  legalOrgName = "Effective Altruism Stuttgart"
  orgLocations = "Stuttgart"
  #registeredCharityNumber = "3.14159"
  contactEmail = "stuttgartea@gmail.com"

  [Languages.de.navbar]
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effektiven Altruismus"
  aboutEA = "Über EA"
  readingMaterial = "Lesematerial"
  keyTerms = "Wichtigste Begriffe"
  organizations = "Organisationen"
  contact= "Kontakt"

  [Languages.de.pages]
  contactPageHeader = "Kontakt"
  aboutEAPageHeader = "Was ist Effektiven Altruismus?"

  [Languages.de.homepage]
  #topBannerText = "Wer sind wir?"
  leadText = "Wir wollen die Welt besser helfen"
  firstSectionHeader = "Mein deutsch..."
  secondSectionHeader = "...ist echt nicht so gut"
  thirdSectionHeader = "Also geb ich auf"
  bottomBannerText = "..und so weiter"

  [Languages.de.contactform]
  leadText = "Sagen Sie Hallo!"
  senderName = "Bitte geben Sie Ihren Namen an (erforderlich)"
  senderEmail = "E-Mail (erforderlich):"
  emailSubject = "Betreff"
  emailMessage = "Nachricht:"
  send = "Abschicken"

  [Languages.de.jumbotron]
  firstButtonText = "Finden Sie uns auf Facebook"
  firstButtonLink = "https://www.facebook.com/groups/eastuttgart/"
  secondButtonText = "E-Mail Newsletter"
  secondButtonLink = "https://groups.google.com/d/forum/eastuttgart"
  meetupButtonText = "Finden Sie uns auf meetup.com"

  [Languages.de.urls]
  facebookUrl = "https://www.facebook.com/groups/eastuttgart/"
  #twitterUrl = ""
  meetupUrl = "https://www.meetup.com/Stuttgart-Effective-Altruism-Meetup"
